import Head from 'next/head';
import Stars from '@/components/universeBg/universe';
import Image from 'next/image';
import './style.css'; // Certifique-se de que este arquivo existe e está no lugar correto
import Bg from '@/components/bg/bg';
import { Chakra_Petch } from 'next/font/google'
import CircleSkils from './components/circle/CircleSkils';
import InfField from './components/InfField/InfField';
import Skill from './components/skills/Skill';
import Certicado from './components/certificado/Certicado';
 
const chakra = Chakra_Petch({
  weight: '400',
  subsets: ['latin'],
})

export default function About() {
  // Estilos inline para o conteúdo
  const relativeStyle: React.CSSProperties = {
    position: 'relative',
    zIndex: 1,
  };

  return (
    <>
      <Head>
        <title>Meu Projeto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Bg/>
      <span id='ef'></span>
      <div id="main_about">
      <div id='b-1'>
        <h2 className={chakra.className}>Sobre mim</h2>
        <p className={chakra.className}>Olá, meu nome é Carlos, e sou um entusiasta apaixonado pelo universo da tecnologia e inovação. Atualmente, estou mergulhado no fascinante mundo da publicidade digital, onde exploro as complexidades e oportunidades do marketing de alto impacto.
          
        </p>
      </div>


      <CircleSkils/>

      <div className="container_">
        <Image
          id="rk"
          src="/about/rk.gif"
          alt="My GIF"
          width={200}
          height={200}
          unoptimized={true}
        />
        <div className="star-field">
          <div className="star"></div>
          <div className="star"></div>
          <div className="star"></div>
          <div className="star"></div>
          <div className="star"></div>
          <div className="star"></div>
        </div>
        <span className={chakra.className} id='tx'>Sempre em busca de conhecimento</span>
      </div>
      {/* <Stars total={400} bg=''/>   */}
    </div>
    <InfField/>
    <Skill/>
    <Certicado/>
    </>
  );
}
