// pages/index.tsx
import Head from 'next/head';
import Stars from '@/components/universeBg/universe';

export default function Home() {
  // Estilos inline para o fundo
  const mainStyle: React.CSSProperties = {
    height: '90vh',
    backgroundImage: 'url("/galaxy2.jpg")',
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    backgroundRepeat: 'no-repeat',
  };

  // Estilos inline para o conteúdo
  const relativeStyle: React.CSSProperties = {
    position: 'relative' as 'relative',
    zIndex: 1,
  };

  return (
    <div style={mainStyle}>
      <Head>
        <title>Meu Projeto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={relativeStyle}>
        <h1 className="text-center text-4xl mt-10">Bem-vindo ao meu projeto!</h1>
        <Stars bg={"/galaxy2.jpg"} total={10000} />
      </div>
    </div>
  );
}
