import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import "./home.css"
import "../components/contacts/Contacts"
import Contacts from "../components/contacts/Contacts";
import ContactMB from "@/components/contacts/ContactMB";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="root">
        <Header/>
        <div className="stars"></div>
        <Contacts/>
        {/* <ContactMB/> */}
        {children}
        <Footer/>
        </body>
    </html>
  );
}
