import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import "./home.css"
import "../components/contacts/Contacts"
import Contacts from "../components/contacts/Contacts";
import 'aos/dist/aos.css';
import FieldContact from "@/components/fieldContact/FieldContact";
import {Theme }from "@/themes/themes-provide";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="root">
        <Theme attribute="class"
               defaultTheme="system"
               enableSystem>
          <Header/>
          <div className="stars"></div>
          <Contacts/>
      
          {children}
          <FieldContact/>
          <Footer/>
        </Theme>
        </body>
    </html>
  );
}
